### PR TITLE
Fixes: not working with OBS v28>, potential security issues from old dependencies. Improves: build size, performance, error handling, ui

### PR DESCRIPTION
**Pull request by quiquelhappy**
- Works with OBS v28 and newer
- Defaults to autostart with VS Code, with improved timings
- Defaults port to default obs-websocket port 4455
- Reduced size considerably
- New indicator icon (bottom right) showing whether the active file is being hidden or not
- Removed connected/disconnected messages in order to avoid clutter when connecting and disconnecting
- "Cut" transition fallback to a "Cut"-alike transition whenever Cut is not found. Will usually default to the equivalent of "Cut" on OBS setups where the locale isn't English

### CODE REVIEW

**Comment by quiquelhappy** [comment]
Feel free to try it out (the zip only contains the .vsix packed extension, github won't let me upload the .vsix itself because of the extension) 
[obs-switcher-0.1.4.zip](https://github.com/ThomasK33/vscode-obs-switcher/files/11185628/obs-switcher-0.1.4.zip)

**Comment by quiquelhappy** [comment]
Hello, this was one month ago, I'll be independently publishing this in few weeks if I don't get any feedback

**Comment by ThomasK33** [comment]
Thanks for your PR, @quiquelhappy.
Your work looks great, but I suggest keeping the default auto-connect function the same, as it may cause errors when OBS isn't running. Most users will likely encounter this scenario, so it's best to keep it false by default. Power users can modify it in the VS Code settings.

I'd merge this and perform a release if you're OK with that.

**Comment by quiquelhappy** [comment]
I believe it is ok to push, specially given that there are plenty of users with lack of support rn, in the future I may revisit this to provide better transition fallback and just polish some things here and there. Have a nice weekend.

**Pull request merged**
